
#https://linuxiac.com/how-to-install-nextcloud-with-docker-compose/

services:
  db:
    image: mariadb:latest
    container_name: db
    networks:
      - pocket5_network
    ports:
      - "3306:3306"
    volumes:
      - ./docker_data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PWD}
    restart: always

  pocket-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pocket-backend:latest
    container_name: pocket-backend
    networks:
      - pocket5_network
    ports:
      - "8081:8081"  
    volumes:
      - ./docker_data/pocket5:/var/www/scripts:ro
    restart: always  
    depends_on:
      - db

networks:
  pocket5_network:
    external: true
