
version: '3.8'

services:
  # MariaDB Database
  pocket-db:
    image: mariadb:latest
    container_name: pocket-db
    networks:
      - pocket-network
    ports:
      - "3306:3306"
    volumes:
      - pocket_db_data:/var/lib/mysql
      - ./scripts/pocket5.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      # Database configuration
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_change_me}
      MARIADB_DATABASE: pocket5
      MARIADB_USER: ${DB_USERNAME:-pocket_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-user_password_change_me}
      # Performance tuning
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: >
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --max-connections=200
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  # Pocket Backend Application
  pocket-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pocket-backend:5.0.0
    container_name: pocket-backend
    networks:
      - pocket-network
    ports:
      - "${SERVER_PORT:-8081}:8081"
    volumes:
      # Application logs
      - pocket_logs:/var/log/pocket
      # Optional: Custom configuration override
      - ./scripts/pocket5-config.yaml:/var/www/scripts/pocket5-config.yaml:ro
    environment:
      # Spring profiles
      SPRING_PROFILES_ACTIVE: docker,production
      
      # Database configuration
      DB_USERNAME: ${DB_USERNAME:-pocket_user}
      DB_PASSWORD: ${DB_PASSWORD:-user_password_change_me}
      
      # Security configuration (MUST BE CHANGED IN PRODUCTION)
      AES_CBC_IV: ${AES_CBC_IV:-default_16char_iv}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-admin_password_change_me}
      
      # Server configuration
      SERVER_URL: ${SERVER_URL:-http://localhost:8081}
      SERVER_PORT: ${SERVER_PORT:-8081}
      
      # CORS configuration
      CORS_ADDITIONAL_ORIGINS: ${CORS_ADDITIONAL_ORIGINS:-}
      
      # Logging configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # JVM configuration
      JAVA_OPTS: >-
        -Xmx${JVM_MAX_MEMORY:-512m}
        -Xms${JVM_MIN_MEMORY:-256m}
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/var/log/pocket/
        -Dfile.encoding=UTF-8
        -Djava.security.egd=file:/dev/./urandom
      
      # Database connection URL (constructed automatically)
      SPRING_DATASOURCE_URL: jdbc:mariadb://pocket-db:3306/pocket5?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&sslMode=DISABLED
      
    restart: unless-stopped
    depends_on:
      pocket-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    
    # Security settings
    user: "1000:1000"  # Run as non-root user
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: pocket-nginx
    networks:
      - pocket-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - BACKEND_HOST=pocket-backend
      - BACKEND_PORT=8081
    depends_on:
      - pocket-backend
    restart: unless-stopped
    profiles:
      - production  # Only start with --profile production

# Named volumes for data persistence
volumes:
  pocket_db_data:
    driver: local
  pocket_logs:
    driver: local
  nginx_logs:
    driver: local

# Custom network for service communication
networks:
  pocket-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
