#spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions: true
#spring.jpa.properties.hibernate.globally_quoted_identifiers: true

spring:
  application.name: Pocket
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  hibernate:
    generate-ddl: true
    ddl-auto: validate
    use-new-id-generator-mappings: true

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/pocket5?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: passwd_to_change

logging:
 level:
   it.salsi.pocket: DEBUG
   hibernate:
     SQL: TRACE
     type: TRACE
   org:
     atmosphere: TRACE
     springframework:
       security: TRACE
       web: DEBUG

server:
  port: 8081
  api-version: /api/v5
  url: http://your_host_or_ip:8081
  socket-port: 8300
  check-timestamp-last-update: false
  services-cron: 1 * * * * ?
  aes.cbc.iv: __iv_to_change__
  auth:
    user: test@test.com
    passwd: ______user_passwd_to_change_____

