spring:
  application.name: Pocket
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  hibernate:
    generate-ddl: true
    ddl-auto: validate
    use-new-id-generator-mappings: true

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
 level:
   it.salsi.pocket: INFO
   hibernate:
     SQL: WARN
     type: WARN
   org:
     atmosphere: WARN
     springframework:
       security: WARN
       web: WARN

server:
  port: ${SERVER_PORT}
  api-version: /api/v5
  url: ${SERVER_URL}
  socket-port: 8300
  check-timestamp-last-update: true
  services-cron: 1 * * * * ?
  tomcat:
    max-http-form-post-size: 10MB
    max-parameter-count: 10000
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
        max-age: 3600

  aes.cbc.iv: ${AES_CBC_IV}
  auth:
    user: ${ADMIN_USER}
    passwd: ${ADMIN_PASSWD}

security:
  headers:
    content-security-policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none';"
  cors:
    additional-origins: ${CORS_ADDITIONAL_ORIGINS}

